### PR TITLE
ci: add --all-features to cargo test

### PR DESCRIPTION
**Pull request by wllenyj**
Asynchronous features testing is required.

Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>

### CODE REVIEW

**Comment by mxpv** [comment]
My understanding is that we have to run tests twice? Sync version (with no features enabled) and async one (with --all-features) ?

**Review by Tim-Zhang — APPROVED** [review]
LGTM

**Comment by Tim-Zhang** [comment]
> My understanding is that we have to run tests twice? Sync version (with no features enabled) and async one (with --all-features) ?

@mxpv sync and async are not conflict with each other.

**Comment by wllenyj** [comment]
@mxpv It can be run together.

**Review by mxpv — APPROVED** [review]
oh, ok. they should :)
LGTM

**Pull request merged**
